name: oction-lock-issue
description: |
  This action implements PUT request to /repos/{owner}/{repo}/issues/{issue_number}/lock

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  owner:
    description: |
      owner parameter
    required: false
  repo:
    description: |
      repo parameter
    required: false
  issue_number:
    description: |
      issue_number parameter
    required: true
  lock_reason:
    description: |
      The reason for locking the issue or pull request conversation. Lock will fail if you don't use one of these reasons:   \* `off-topic`   \* `too heated`   \* `resolved`   \* `spam`
    required: 

runs:
  using: node12
  main: index.js

branding:
  icon: lock
  color: gray-dark
